#!/bin/bash

# Obelisk Core PM2 Manager
# Manages the Obelisk Core API server with PM2
# Auto-generates ecosystem config, manages logs, and handles restarts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$SCRIPT_DIR/logs"
ECOSYSTEM_FILE="$SCRIPT_DIR/ecosystem.config.js"
SERVICE_NAME="obelisk-core"
DEFAULT_PORT="${OBELISK_CORE_PORT:-7779}"
DEFAULT_HOST="${OBELISK_CORE_HOST:-0.0.0.0}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Ensure log directory exists
mkdir -p "$LOG_DIR"

# Check if PM2 is installed
if ! command -v pm2 &> /dev/null; then
    echo -e "${RED}❌ PM2 is not installed. Installing...${NC}"
    npm install -g pm2
fi

# Check if PM2 logrotate is installed and configured
setup_logrotate() {
    if ! pm2 list 2>/dev/null | grep -q "pm2-logrotate"; then
        echo -e "${YELLOW}⚠️  PM2 logrotate not found. Installing...${NC}"
        pm2 install pm2-logrotate
    fi

    # Configure PM2 logrotate
    pm2 set pm2-logrotate:max_size 10M
    pm2 set pm2-logrotate:retain 7
    pm2 set pm2-logrotate:compress true
    pm2 set pm2-logrotate:dateFormat YYYY-MM-DD_HH-mm-ss
    pm2 set pm2-logrotate:workerInterval 30
    pm2 set pm2-logrotate:rotateInterval "0 0 * * *"
    pm2 set pm2-logrotate:rotateModule true
    echo -e "${GREEN}✅ PM2 logrotate configured${NC}"
}

# Generate ecosystem config (avoids hardcoded paths in repo)
generate_ecosystem() {
    cat > "$ECOSYSTEM_FILE" << ECOSYSTEMEOF
// Auto-generated by pm2-manager.sh — do not edit manually
const path = require('path');

module.exports = {
  apps: [
    {
      name: '${SERVICE_NAME}',
      script: path.resolve(__dirname, 'venv/bin/python'),
      args: '-m uvicorn src.api.server:app --host ${DEFAULT_HOST} --port ${DEFAULT_PORT} --no-access-log',
      interpreter: 'none',
      cwd: path.resolve(__dirname),
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PYTHONUNBUFFERED: '1',
        OBELISK_CORE_PORT: '${DEFAULT_PORT}',
        OBELISK_CORE_HOST: '${DEFAULT_HOST}',
      },
      // Combined log in logs folder
      log_file: path.resolve(__dirname, 'logs', 'obelisk-core.log'),
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
    }
  ]
};
ECOSYSTEMEOF
    echo -e "${GREEN}✅ Ecosystem config generated at ${ECOSYSTEM_FILE}${NC}"
}

# Function to check if service exists in PM2
service_exists() {
    pm2 list 2>/dev/null | grep -q "$SERVICE_NAME"
}

# Function to check if service is actually running (online)
is_running() {
    if service_exists; then
        pm2 list 2>/dev/null | grep "$SERVICE_NAME" | grep -q "online"
    else
        return 1
    fi
}

# Function to delete logs
delete_logs() {
    if [ -d "$LOG_DIR" ]; then
        echo -e "${YELLOW}🗑️  Deleting all logs...${NC}"
        rm -f "$LOG_DIR"/*.log* 2>/dev/null || true
        rm -f "$LOG_DIR"/*.gz 2>/dev/null || true
        echo -e "${GREEN}✅ All logs deleted${NC}"
    fi
}

# Function to start service
start() {
    if is_running; then
        echo -e "${YELLOW}⚠️  ${SERVICE_NAME} is already running${NC}"
        pm2 list | grep "$SERVICE_NAME"
        return 1
    fi

    # If service exists but is stopped, delete it first
    if service_exists; then
        echo -e "${YELLOW}⚠️  Found stopped ${SERVICE_NAME}. Removing it first...${NC}"
        pm2 delete "$SERVICE_NAME" 2>/dev/null || true
        pm2 save
    fi

    echo -e "${BLUE}🚀 Starting ${SERVICE_NAME}...${NC}"

    # Check virtual environment
    if [ ! -d "$SCRIPT_DIR/venv" ]; then
        echo -e "${RED}❌ Virtual environment not found at $SCRIPT_DIR/venv${NC}"
        echo -e "${YELLOW}   Run: python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt${NC}"
        return 1
    fi

    if [ ! -f "$SCRIPT_DIR/venv/bin/python" ]; then
        echo -e "${RED}❌ Python interpreter not found in virtual environment.${NC}"
        return 1
    fi

    # Setup logrotate on first start
    setup_logrotate

    # Generate ecosystem config
    generate_ecosystem

    # Start with PM2
    cd "$SCRIPT_DIR"
    pm2 start ecosystem.config.js --update-env

    # Save PM2 process list
    pm2 save

    echo -e "${GREEN}✅ ${SERVICE_NAME} started on port ${DEFAULT_PORT}${NC}"
    pm2 list | grep "$SERVICE_NAME"
}

# Function to stop service
stop() {
    if ! service_exists; then
        echo -e "${YELLOW}⚠️  ${SERVICE_NAME} is not registered${NC}"
        return 1
    fi

    if ! is_running; then
        echo -e "${YELLOW}⚠️  ${SERVICE_NAME} is already stopped${NC}"
        pm2 list | grep "$SERVICE_NAME"
        return 1
    fi

    echo -e "${BLUE}🛑 Stopping ${SERVICE_NAME}...${NC}"
    pm2 stop "$SERVICE_NAME"
    pm2 save
    echo -e "${GREEN}✅ ${SERVICE_NAME} stopped${NC}"
}

# Function to restart service
restart() {
    if ! service_exists; then
        echo -e "${YELLOW}⚠️  ${SERVICE_NAME} is not registered. Starting...${NC}"
        start
        return
    fi

    echo -e "${BLUE}🔄 Restarting ${SERVICE_NAME}...${NC}"

    # Delete logs on restart
    delete_logs

    # Re-generate ecosystem config in case env changed
    generate_ecosystem

    # If service is stopped, delete and start fresh
    if ! is_running; then
        echo -e "${YELLOW}⚠️  Service is stopped. Removing and starting fresh...${NC}"
        pm2 delete "$SERVICE_NAME" 2>/dev/null || true
        cd "$SCRIPT_DIR"
        pm2 start ecosystem.config.js --update-env
    else
        pm2 restart "$SERVICE_NAME" --update-env
    fi

    pm2 save
    echo -e "${GREEN}✅ ${SERVICE_NAME} restarted${NC}"
    pm2 list | grep "$SERVICE_NAME"
}

# Function to restart all and delete logs
restart_all() {
    echo -e "${BLUE}🔄 Full restart: deleting logs and starting fresh...${NC}"

    # Delete service if it exists
    if service_exists; then
        pm2 delete "$SERVICE_NAME" 2>/dev/null || true
    fi

    # Delete all logs
    delete_logs

    # Start fresh
    start

    pm2 save
    echo -e "${GREEN}✅ ${SERVICE_NAME} restarted fresh with clean logs${NC}"
    pm2 list | grep "$SERVICE_NAME"
}

# Function to show status
status() {
    echo -e "${BLUE}📊 ${SERVICE_NAME} Status:${NC}"
    if service_exists; then
        pm2 list | grep "$SERVICE_NAME"
        if is_running; then
            echo ""
            echo -e "${BLUE}📋 Recent logs:${NC}"
            pm2 logs "$SERVICE_NAME" --lines 10 --nostream
        else
            echo -e "${YELLOW}⚠️  Service is registered but not running${NC}"
        fi
    else
        echo -e "${RED}❌ ${SERVICE_NAME} is not registered${NC}"
    fi
}

# Function to show logs
logs() {
    if ! service_exists; then
        echo -e "${RED}❌ ${SERVICE_NAME} is not registered${NC}"
        return 1
    fi

    if ! is_running; then
        echo -e "${YELLOW}⚠️  ${SERVICE_NAME} is not running. Showing last logs...${NC}"
    fi

    echo -e "${BLUE}📋 Showing ${SERVICE_NAME} logs (Ctrl+C to exit):${NC}"
    pm2 logs "$SERVICE_NAME"
}

# Function to show log files
log_files() {
    echo -e "${BLUE}📁 Log files:${NC}"
    if [ -d "$LOG_DIR" ] && [ "$(ls -A "$LOG_DIR" 2>/dev/null)" ]; then
        ls -lh "$LOG_DIR" 2>/dev/null
    else
        echo -e "${YELLOW}No log files found${NC}"
    fi
}

# Function to show help
help() {
    echo -e "${BLUE}Obelisk Core PM2 Manager${NC}"
    echo ""
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  start         Start the Obelisk Core server"
    echo "  stop          Stop the Obelisk Core server"
    echo "  restart       Restart server and delete logs"
    echo "  restart-all   Full restart: delete everything and start fresh"
    echo "  status        Show service status and recent logs"
    echo "  logs          Show live logs (Ctrl+C to exit)"
    echo "  log-files     List log files and sizes"
    echo "  help          Show this help message"
    echo ""
    echo "Environment:"
    echo "  OBELISK_CORE_PORT  Server port (default: 7779)"
    echo "  OBELISK_CORE_HOST  Server host (default: 0.0.0.0)"
    echo ""
}

# Main command handler
case "${1:-help}" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    restart-all)
        restart_all
        ;;
    status)
        status
        ;;
    logs)
        logs
        ;;
    log-files)
        log_files
        ;;
    help|--help|-h)
        help
        ;;
    *)
        echo -e "${RED}❌ Unknown command: $1${NC}"
        help
        exit 1
        ;;
esac
