// This file will be generated by running: npm run cf-typegen
// For now, we'll define a basic interface

interface CloudflareEnv {
  // Add your Cloudflare bindings here
  // Example:
  // MY_KV: KVNamespace;
  // MY_D1: D1Database;
  // MY_R2: R2Bucket;
}
