// Import all node types to register them with Litegraph
import "./TextNode";
import "./InferenceConfigNode"; // Replaces ModelLoaderNode — configures inference service endpoint
// NOTE: LoRA is not supported via the inference service yet.
// import "./LoRALoaderNode";
import "./MemoryStorageNode";
import "./MemorySelectorNode";
import "./MemoryCreatorNode";
import "./InferenceNode";
import "./TelegramBotNode";
import "./TelegramListenerNode";
import "./SchedulerNode";
import "./TelegramMemoryCreatorNode";
import "./TelegramMemorySelectorNode";
import "./BinaryIntentNode";
import "./BooleanLogicNode";
import "./RerouteNode";
import "./HttpListenerNode";
import "./HttpResponseNode";
import "./ExpressServiceNode";
import "./AutotraderStatsListenerNode";
import "./ClankerAutotraderStatsNode";
import "./SellBagsListenerNode";
import "./SellAllBagsNode";
import "./ActionLoggerNode";
import "./ActionRouterNode";
import "./TelegramActionNode";
import "./BlockchainConfigNode";
import "./ClankerTokenStatsNode";
import "./ClankerLaunchSummaryNode";
import "./WalletNode";
import "./BalanceCheckerNode";
import "./ClankerBuyNode";
import "./ClankerSellNode";
import "./BuyNotifyNode";
import "./OnSwapTriggerNode";
import "./BagCheckerNode";
import "./AddToBagsNode";
import "./UpdateBagsOnSellNode";
import "./SellNotifyNode";